### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by SimonCropp**

### CODE REVIEW

**Comment by SimonCropp** [comment]
feel free to cherry pick any of these, or let me know if u want any split out to individual PRs

**Comment by hakenmt** [comment]
So, I purposefully targetted netstandard1.6 (including other dependencies like JSON.NET) so that this library would be compatible on AWS Lambda. I don't think targeting both netstandard1.6 and netstandard2.0 does anything or am I mistaken? I'll take a look through the rest of your PR content and update some things.

**Comment by SimonCropp** [comment]
yeah my understanding of netstandard2.0 it is results in a smaller dependency tree. since more stuff is included in the runtime

**Comment by SimonCropp** [comment]
it is why many libs multitarget a 1.x and 2.0. eg https://github.com/AutoMapper/AutoMapper/blob/master/src/AutoMapper/AutoMapper.csproj#L6

**Pull request closed without merging**
